### PR TITLE
Proposed changes to address Issue 56

### PR DESCRIPTION
**Pull request by triplingual**
Honestly, I haven't been able to get `limit` and `offset` to work, but otherwise I think this is accurate.

### CODE REVIEW

**Comment by zerocrates** [comment]
> Honestly, I haven't been able to get limit and offset to work

Basically, `limit` and `offset` are designed for use in the PHP-side API endpoint, not the REST: the browse actions and the API "search" operation both automatically imply use of the pagination system, and when that's being used, `limit` and `offset` are ignored.

**Comment by zerocrates** [comment]
I agree that we should include these default values in the documentation.

One minor note on the defaults you've listed: the default per page limit is controlled by the global "results per page" setting, so it can differ from installation to installation.

**Comment by triplingual** [comment]
Changed `per_page` default column value from 25 to "uses [global 'results per page' setting](https://omeka.org/s/docs/user-manual/admin/settings/#general)".

Is this a brittle or undesirable link? I don't have a sense of whether you're trying to keep dev and end-user doco wholly separate.

**Comment by zerocrates** [comment]
I don't think there's any problem linking between the developer and user documentation like that.

**Pull request merged**
